app.py
from flask import Flask, render_template, redirect, url_for, session
from views import views
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired, Email, Length

app = Flask(__name__)
app.config['SECRET_KEY'] = 'Thisissupposedtobesecret!'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + 'database.db'
Bootstrap(app)
db = SQLAlchemy(app)

app.register_blueprint(views)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(80))

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=4, max=15)])
    email = StringField('Email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('Remember me')

@app.route('/', methods=['GET', 'POST'])
def register():
    form2 = LoginForm()
    if form2.validate_on_submit():
        user = User.query.filter_by(username=form2.username.data).first()
        if user:
            if user.password == form2.password.data:
                return redirect(url_for('dashboard'))
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        db.session.add(new_user)
        db.session.commit()
        return '<h1>New user has been registered!</h1>'
    return render_template('index.html', form=form, form2=form2)

if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, Blueprint
from random import randint

views = Blueprint('views', __name__)

@views.route('/lol')
def lol():
    return render_template('lol.html')

@views.route('/pokemon')
def pokemon():
    return render_template('pokemon.html')

@views.route('/familyguy')
def familyguy():
    return render_template('familyguy.html')

@views.route('/games.html')
def games():
    return render_template('games.html')

@views.route('/tvseries.html')
def tvseries():
    return render_template('tvseries.html')

@views.route('/movies.html')
def movies():
    return render_template('movies.html')

@views.route('/random')
def random():
    page=randint(1,3)
    if page ==1:
        return render_template('familyguy.html')
    elif page ==2:
        return render_template('pokemon.html')
    elif page ==3:
        return render_template('lol.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="/static/js/main.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <title>Mysterylink</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<body id="home">
    <h1>MYSTERY LINK</h1>
    <h2 class="page-header" id="bright">Welcome, {{ name }}</h2>
    <nav>
        <a href="{{ url_for('views.lol') }}">LOL</a>
        <a href="{{ url_for('views.pokemon') }}">Pokemon</a>
        <a href="{{ url_for('views.familyguy') }}">Family Guy</a>
    </nav>
</body>
{% endblock %}

templates/games.html
{% extends 'base.html' %}
{% block content %}
<body class="bodyex gamebody">
    <div>
        <h1 class="top">POKÉMON</h1>
    </div>
    <nav>
        <a href="{{ url_for('views.pokemon') }}" class="custom-nav-links">HOME</a>
        <a href="{{ url_for('views.games') }}" class="custom-nav-links">GAMES</a>
        <a href="{{ url_for('views.tvseries') }}" class="custom-nav-links">TV SERIES</a>
        <a href="{{ url_for('views.movies') }}" class="custom-nav-links">MOVIES</a>
    </nav>
    <div id="pokebox">
        <h2 class="head">POKÉMON GAMES & APPS:</h2>
        <ol>
            <li>Pocket Monsters Red and Green (1996)</li>
            <li>Pocket Monsters Blue (1996)</li>
            <br>
            <li>Pocket Monsters Stadium (1998)</li>
            <li>Pokémon Yellow: Special Pikachu Edition (1998)</li>
            <li>Hey You, Pikachu! (1998)</li>
            <li>Pokémon Trading Card Game (1998)</li>
            <br>
            <li>Pokémon Snap (1999)</li>
            <li>Pokémon Pinball (1999)</li>
            <li>Pokémon Stadium (1999)</li>
            <li>Pokémon Project Studio (1999)</li>
            <li>Pokémon Gold and Silver (1999)</li>
            <li>Pokémon Play It! (1999)</li>
            <br>
            <li>Pokémon PokéROM Gotta Learn 'em All! (2000)</li>
            <li>Pokémon Play It! Version 2 (2000)</li>
            <li>Pokémon Puzzle Challenge (2000)</li>
            <li>Pokémon Puzzle League (2000)</li>
            <li>Pokémon Crystal (2000)</li>
            <li>Pokémon 2000 (2000)</li>
            <li>Pokémon Stadium 2 (2000)</li>
            <br>
            <li>Pokémon Party Mini (2001)</li>
            <li>Pokémon Pinball Mini (2001)</li>
            <li>Pokémon Puzzle Collection (2001)</li>
            <li>Pokémon Puzzle Collection Vol. 2 (2001)</li>
            <li>Pokémon Zany Cards (2001)</li>
            <li>Pokémon Tetris (2001)</li>
            <li>Pokémon Race Mini (2001)</li>
            <li>Pichu Bros. Mini (2001)</li>
            <li>Togepi's Great Adventure (2001)</li>
            <li>Pokémon Breeder Mini (2001)</li>
            <li>Pokémon Card GB2: Here Comes Great Team Rocket! (2001)</li>
            <br>
            <li>Pokémon: Catch the Numbers! (2002)</li>
            <li>Pokémon Ruby and Sapphire (2002)</li>
            <br>
            <li>Pokémon Box: Ruby and Sapphire (2003)</li>
            <li>Pokémon Channel (2003)</li>
            <li>Pokémon Pinball: Ruby & Sapphire (2003)</li>
            <li>Pokémon Advanced Generation: I've Begun Hiragana and Katakana! (2003)</li>
            <li>Pokémon Colosseum (2003)</li>
            <br>
            <li>Pokémon: Masters Arena (2004)</li>
            <li>Pokémon FireRed and LeafGreen (2004)</li>
            <li>Pokémon Advanced Generation: Pico for Everyone Pokémon Loud Battle! (2004)</li>
            <li>Pokémon Emerald (2004)</li>
            <li>Pokémon Dash (2004)</li>
            <br>
            <li>Pokémon XD: Gale of Darkness (2005)</li>
            <li>Pokémon Advanced Generation: Pokémon Number Battle! (2005)</li>
            <li>Pokémon Trozei! (2005)</li>
            <li>Pokémon: Team Turbo (2005)</li>
            <li>Pokémon Mystery Dungeon: Blue Rescue Team and Red Rescue Team (2005)</li>
            <br>
            <li>Pokémon Team Rocket Blast Off (2006)</li>
            <li>Pokémon Poké Ball Launcher (2006)</li>
            <li>Pokémon Seek & Find (2006)</li>
            <li>Pokémon Ranger (2006)</li>
            <li>Pokémon PC Master (2006)</li>
            <li>Pokémon Diamond and Pearl (2006)</li>
            <li>Pokémon Battle Revolution (2006)</li>
            <li>Pokémate (2006)</li>
            <br>
            <li>Intellectual Training Drill Pokémon Diamond and Pearl: Letter and Number Intelligence Game (2007)</li>
            <li>Pokémon Mystery Dungeon: Explorers of Time and Explorers of Darkness (2007)</li>
            <li>Pokémon Battrio (2007)</li>
            <br>
            <li>Pokémon Ranger: Shadows of Almia (2008)</li>
            <li>My Pokémon Ranch (2008)</li>
            <li>Pokémon Platinum (2008)</li>
            <br>
            <li>Pokémon Mystery Dungeon: Explorers of Sky (2009)</li>
            <li>Pokémon Rumble (2009)</li>
            <li>Pokémon Mystery Dungeon: Keep Going! Blazing Adventure Squad!,<br>Let's Go! Stormy Adventure Squad!, and Go For It! Light Adventure Squad! (2009)</li>
            <li>Pokémon HeartGold and SoulSilver (2009)</li>
            <li>Pokémon Diamond and Pearl: Search for Pokémon! Adventure in the Maze! (2009)</li>
            <li>Pokémon Card Game Online (2009)</li>
            <li>PokéPark Wii: Pikachu's Adventure (2009)</li>
            <br>
            <li>Pokémon Ranger: Guardian Signs (2010)</li>
            <li>Pokémon Black and White (2010)</li>
            <li>Pokémon Best Wishes: Intelligence Training Pokémon Big Sports Meet! (2010)</li>
            <br>
            <li>Pokémon TCG Online (2011)</li>
            <li>Learn with Pokémon: Typing Adventure (2011)</li>
            <li>Pokémon Card Game: How To Play DS (2011)</li>
            <li>Pokémon Rumble Blast (2011)</li>
            <li>PokéPark 2: Wonders Beyond (2011)</li>
            <br>
            <li>Pokémon TCG Online (2012)</li>
            <li>Pokémon Conquest (2012)</li>
            <li>Pokèmon Dream Radar (2012)</li>
            <li>Pokémon Black 2 and White 2 (2012)</li>
            <li>Pokémon Tretta (2012)</li>
            <li>Pokédex 3D and Pokédex 3D Pro (2012)</li>
            <li>Pokémon Mystery Dungeon: Gates to Infinity (2012)</li>
            <br>
            <li>Pokémon Rumble U (2013)</li>
            <li>Pokémon Tretta Lab (2013)</li>
            <li>Pokémon X and Y (2013)</li>
            <li>Pokémon Bank (2013)</li>
            <br>
            <li>Pokémon Battle Trozei (2014)</li>
            <li>Pokémon Art Academy (2014)</li>
            <li>Camp Pokémon (2014)</li>
            <li>Pokémon Omega Ruby and Alpha Sapphire (2014)</li>
            <br>
            <li>Pokémon Shuffle (2015)</li>
            <li>Pokémon Rumble World (2015)</li>
            <li>Pokkén Tournament (2015)</li>
            <li>Pokémon Super Mystery Dungeon (2015)</li>
            <li>Pokémon Picross (2015)</li>
            <br>
            <li>Detective Pikachu (2016)</li>
            <li>Pokémon Go (2016)</li>
            <li>Pokémon Ga-Olé (2016)</li>
            <li>Pokémon Sun and Moon (2016)</li>
            <br>
            <li>Pokémon Duel (2017)</li>
            <li>Pokémon: Magikarp Jump (2017)</li>
            <li>Pokkén Tournament DX (2017)</li>
            <li>Pokémon Playhouse (2017)</li>
            <li>Pokémon Ultra Sun and Ultra Moon (2017)</li>
            <br>
            <li>Pokémon Quest (2018)</li>
            <li>Pokémon: Let's Go, Pikachu! and Let's Go, Eevee! (2018)</li>
            <br>
            <li>Pokémon Trading Card Game Card Dex (2019)</li>
            <li>Pokémon Rumble Rush (2019)</li>
            <li>Pokémon Masters Ex (2019)</li>
            <li>Pokémon Sword and Shield (2019)</li>
            <li>Pokémon Medallion Battle (2019)</li>
            <li>Pokémon Tower Battle (2019)</li>
            <br>
            <li>Pokémon Home (2020)</li>
            <li>Pokémon Mystery Dungeon: Rescue Team DX (2020)</li>
            <li>Pokémon Smile (2020)</li>
            <li>Pokémon Café Mix (2020)</li>
            <li>Pokémon Mezastar (2020)</li>
            <br>
            <li>New Pokémon Snap (2021)</li>
            <li>Pokémon Unite (2021)</li>
            <li>Pokémon Brilliant Diamond and Shining Pearl (2021)</li>
            <br>
            <li>Pokémon Legends: Arceus (2022)</li>
            <li>Pokémon Scarlet and Violet (2022)</li>
        </ol>
    </div>
</body>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<body class="home" id="dark-mode">
    <div class="darkedit">
        <button onclick="darkMode()" class="buttnaked">Colour Mode</button>
    </div>
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
    <div class="mystery">
        <a href="{{ url_for('views.random') }}" target='_blank' id="mystery">Mystery Link</a>
    </div>
    <div class="registeredit">
        <button type="button" class="buttnaked error">
            Register / Login
        </button>
        <!-- <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="buttnaked">
            Register/Login
        </button> -->
    </div>
    <!-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sign up</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="form-signin" action="/" method="POST">
                        <h2 class="form-signin-heading">Sign up here</h2>
                        {{ form.hidden_tag() }}
                        {{ wtf.form_field(form.username) }}
                        {{ wtf.form_field(form.email) }}
                        {{ wtf.form_field(form.password) }}
                        <button type="submit">Register</button>
                    </form>
                    <form class="form-signin" action="/" method="POST">
                        <h2 class="form-signin-heading">Sign in here</h2>
                        {{ form2.hidden_tag() }}
                        {{ wtf.form_field(form2.username) }}
                        {{ wtf.form_field(form2.password) }}
                        {{ wtf.form_field(form2.remember) }}
                        <button type="submit">Sign in</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button">Submit</button>
                </div>
            </div>
        </div>
    </div> -->
</body>
{% endblock %}

templates/lol.html
{% extends 'base.html' %}

{% block content %}
<body class='lolimg bodyex'>
    <div id="lolcontainer">
        <audio src="/static/audio/cartman.mp3" type="audio/mpeg" autoplay loop controls id="audiomargin"></audio>
        <p id="lolmargin">This is a page that has the primary purpose to annoy the hell out of you with Cartmans laugh!<br>However, should your browser detect the autoplay... you are one lucky SOB.</p>
    </div>
</body>
{% endblock %}

templates/movies.html
{% extends 'base.html' %}
{% block content %}
<body class="bodyex moviebody">
    <div>
        <h1 class="top">POKÉMON</h1>
    </div>
    <nav>
        <a href="{{ url_for('views.pokemon') }}" class="custom-nav-links">HOME</a>
        <a href="{{ url_for('views.games') }}" class="custom-nav-links">GAMES</a>
        <a href="{{ url_for('views.tvseries') }}" class="custom-nav-links">TV SERIES</a>
        <a href="{{ url_for('views.movies') }}" class="custom-nav-links">MOVIES</a>
    </nav>
    <div id="pokebox">
        <h2 class="head">POKÉMON MOVIES</h2>
        <ol>
            <li>Pokémon: The First Movie - Mewtwo Strikes Back (1999)</li>
            <li>Pokémon: The Movie 2000 - The Power of One (2000)</li>
            <li>Pokémon 3: The Movie - Spell of the Unown (2001)</li>
            <li>Pokémon 4Ever: Celebi - Voice of the Forest (2002)</li>
            <li>Pokémon Heroes: Latios and Latias (2003)</li>
            <li>Pokémon: Jirachi - Wish Maker (2004)</li>
            <li>Pokémon: Destiny Deoxys (2005)</li>
            <li>Pokémon: Lucario and the Mystery of Mew (2006)</li>
            <li>Pokémon Ranger and the Temple of the Sea (2007)</li>
            <li>Pokémon: The Rise of Darkrai (2008)</li>
            <li>Pokémon: Giratina & the Sky Warrior (2008)</li>
            <li>Pokémon: Arceus and the Jewel of Life (2009)</li>
            <li>Pokémon - Zoroark: Master of Illusions (2010)</li>
            <li>Pokémon the Movie: Black - Victini and Reshiram, White - Victini and Zekrom (2011)</li>
            <li>Pokémon the Movie: Kyurem vs. the Sword of Justice (2012)</li>
            <li>Pokémon the Movie: Genesect and The Legend Awakened (2013)</li>
            <li>Pokémon the Movie: Diancie and the Cocoon of Destruction (2014)</li>
            <li>Pokémon the Movie: Hoopa and the Clash of Ages (2015)</li>
            <li>Pokémon the Movie: Volcanion and the Mechanical Marvel (2016)</li>
            <li>Pokémon the Movie: I Choose You! (2017)</li>
            <li>Pokémon the Movie: The Power of Us (2018)</li>
            <li>Detective Pikachu (2019)</li>
            <li>Pokémon: Mewtwo Strikes Back: Evolution (2020)</li>
            <li>Pokémon the Movie: Secrets of the Jungle (2021)</li>
        </ol>
    </div>
</body>
{% endblock %}

templates/pokemon.html
{% extends 'base.html' %}
{% block content %}
<body class="bodyex pokebody">
    <div>
        <h1 class="top">POKÉMON</h1>
    </div>
    <nav>
        <a href="{{ url_for('views.pokemon') }}" class="custom-nav-links">HOME</a>
        <a href="{{ url_for('views.games') }}" class="custom-nav-links">GAMES</a>
        <a href="{{ url_for('views.tvseries') }}" class="custom-nav-links">TV SERIES</a>
        <a href="{{ url_for('views.movies') }}" class="custom-nav-links">MOVIES</a>
    </nav>
    <div id="pokebox">
        <h2 class="head">Interested in the pocket monsters?</h2>
        <p>Within the Pokémon universe, the little monster-like beings roam the world alongside humans!<br>Wether you are reading, playing or watching Pokémon media, you will always feel a sense of adventure and exploration!<br>There are currently 913 species of Pokémon split throughout the 9 generations with more to be announced from Scarlet & Violet later this year (2022).<br><br>In 1996 Satoshi Tajiri created his original work: Pocket Monsters Red and Green.<br>The pair of Game Boy video games were developed by Game Freak and published by Nintendo.<br>Following numerous remakes and spin-offs, the collection of Pokémon games continues to expand and you may click the link above to see the current list of released Pokémon games.<br><br>The TV Series of Pokémon is also always expanding, almost parallel to the extensive list of Pokémon movies! Feel free to use the links above to see the released media.
        </p>
    </div>
</body>
{% endblock %}

templates/tvseries.html
{% extends 'base.html' %}
{% block content %}
<body class="bodyex tvbody">
    <div>
        <h1 class="top">POKÉMON</h1>
    </div>
    <nav>
        <a href="{{ url_for('views.pokemon') }}" class="custom-nav-links">HOME</a>
        <a href="{{ url_for('views.games') }}" class="custom-nav-links">GAMES</a>
        <a href="{{ url_for('views.tvseries') }}" class="custom-nav-links">TV SERIES</a>
        <a href="{{ url_for('views.movies') }}" class="custom-nav-links">MOVIES</a>
    </nav>
    <div id="pokebox">
        <h2 class="head">POKÉMON TV SERIES</h2>
        <ol>
            <li>Pokémon: Indigo League (79 Episodes)</li>
            <li>Pokémon: Adventures in the Orange Islands (36 Episodes)</li>
            <li>Pokémon: The Johto Journeys (41 Episodes)</li>
            <li>Pokémon: Johto League Champions (52 Episodes)</li>
            <li>Pokémon: Master Quest (64 Episodes)</li>
            <li>Pokémon: Advanced (40 Episodes)</li>
            <li>Pokémon: Advanced Challenge (52 Episodes)</li>
            <li>Pokémon: Advanced Battle (52 Episodes)</li>
            <li>Pokémon: Battle Frontier (47 Episodes)</li>
            <li>Pokémon: Diamond and Pearl (51 Episodes)</li>
            <li>Pokémon: DP Battle Dimension (52 Episodes)</li>
            <li>Pokémon: DP Galactic Battles (52 Episodes)</li>
            <li>Pokémon: DP Sinnoh League Victors (34 Episodes)</li>
            <li>Pokémon: Black & White (48 Episodes)</li>
            <li>Pokémon: BW Rival Destinies (49 Episodes)</li>
            <li>Pokémon: BW Adventures in Unova and Beyond (45 Episodes)</li>
            <li>Pokémon the Series: XY (48 Episodes)</li>
            <li>Pokémon the Series: XY Kalos Quest (45 Episodes)</li>
            <li>Pokémon the Series: XYZ (48 Episodes)</li>
            <li>Pokémon the Series: Sun & Moon (43 Episodes)</li>
            <li>Pokémon the Series: Sun & Moon - Ultra Adventures (48 Episodes)</li>
            <li>Pokémon the Series: Sun & Moon - Ultra Legends (54 Episodes)</li>
            <li>Pokémon Journeys: The Series (48 Episodes)</li>
            <li>Pokémon Master Journeys: The Series (42 Episodes)</li>
            <li>Pokémon Ultimate Journeys: The Series (Ongoing)</li>
        </ol>
    </div>
</body>
{% endblock %}